var a = 5;
var b = 6;
console.log("Before swap : a = ", a, "b = ", b);
var temp = a;
a = b;
b= temp;
console.log("After swap: a=", a, "b = ", b);
var x = 6;
var y = 7;
x = x + y;
y = x - y;
x = x - y;
console.log("after swap: x=", x, "y = ", y);
